site_title: "ICM Text"
home_md: "README.md"
nav:
  - Home: "README.md"
  - Chapters: "chapters.md"
  - GitHub: "https://github.com/chrisdonahue/icm-text"
variables:
  - "$MYVARIABLE1": "foo"
  - "$MYVARIABLE2": "bar"
